### ISSUE TITLE
Pass if Equal fails two equal values if they are different datatypes

### ISSUE THREAD

**Issue by gt-thetic** [Astemes/astemes-lunit#7]
This may be intentional, but unintuitive. Please close the issue if this is intended behavior. 
When using Pass if Equal, if you pass the same value, for example ```16``` as the 'expected' as a u32, but the actual is ```16``` as a I32, the test returns as Failed.  If you convert the actual ```to U32```, the test passes.
![image](https://github.com/Astemes/astemes-lunit/assets/131265119/a172dbf3-72f6-4093-8487-4d2a2c24b316)
![image](https://github.com/Astemes/astemes-lunit/assets/131265119/4a8d61e1-d5d0-4127-b1e0-3cbf95f706f9)

**Comment by antsundq** [comment]
Yes, this is intentional, but it might not be the "right" thing to do. 

In version v1.3.10 I added more details to the description on type errors, as below.
![image](https://github.com/Astemes/astemes-lunit/assets/40723774/e6ced1f0-9469-41c1-b8f9-41b577f88829)

Do you think this is enough to make it more intuitive? Another option would be to add a flag for strict matching, but it would add to the clutter and decrease readability. I have found cases, especially when working with low-level communication, where the type is very important and should fail the test.

**Comment by gt-thetic** [comment]
I think your screenshot is sufficient enough to explain that a difference exists and anyone with knowledge required to perform Unit Tests should be able to infer that this is the intended behavior.  I think it's quite powerful if it can detect type and doesn't coerce.

**Comment by antsundq** [comment]
Great feedback, thanks!
I’ll close this one then.
